name: Pipeline MLOps - Validation des Modèles

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Récupération du code source
        uses: actions/checkout@v4

      - name: 2. Construction de l'image Docker
        run: docker build -t projet-mlops .

      - name: 3. Exécution du pipeline de Régression (Headless)
        run: docker run projet-mlops python -m jupyter nbconvert --to notebook --execute Projet_Partie_Regression.ipynb

      - name: 4. Exécution du pipeline de Classification (Headless)
        run: docker run projet-mlops python -m jupyter nbconvert --to notebook --execute Projet_Partie_Classification.ipynb